# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist, github-pages]

# Permalinks
permalink:        pretty

# Setup
title:            'Yash Aggarwal'
tagline:          'A Jekyll theme'
description:      'UT Austin Computer Science. I love tech, basketball, music, and education. I really love combinations of them.'
url:              http://www.yashaggarwal.com
baseurl:          /

author:
  name:           'Yash Aggarwal'
  url:            http://www.yashaggarwal.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

paginate_path: "blog/:num/"
