# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Yash Aggarwal'
tagline:          'A Jekyll theme'
description:      'UT Austin Computer Science. I love tech, basketball, music, and education. I really love combinations of them.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

paginate_path: "blog/:num/"
